package jvm

import (
	"errors"
	"fmt"
	"sort"
	"strings"
)

// Supported stub frameworks.
const (
	FrameworkTestNG = "testng"
	FrameworkJUnit5 = "junit5"
)

// StubCase is one Observo case rendered into a @Test method skeleton.
type StubCase struct {
	Code        string   // e.g. "PD-101" → join tag
	Name        string   // → backtick fun name
	Description string   // → @Description (omitted when empty)
	Layer       string   // "API" | "E2E" | "UNIT" — a KDoc note, NOT part of the join
	Steps       []string // rendered as body comments; may be empty
}

// StubClass groups cases that share one Observo suite into a single Kotlin
// test class (suite → class, case → @Test method).
type StubClass struct {
	Package   string // Kotlin package; "" → no package line
	ClassName string // PascalCase, conventionally ends with "Test"
	Feature   string // Observo suite name → @Feature (omitted when empty)
	Cases     []StubCase
}

// RenderKotlin renders a StubClass into a compilable Kotlin test skeleton
// for the given framework ("testng" | "junit5"). The join tag and Allure
// metadata are wired; the body is a TODO the developer fills in.
func RenderKotlin(cls StubClass, framework string) (string, error) {
	framework = strings.ToLower(strings.TrimSpace(framework))
	if framework != FrameworkTestNG && framework != FrameworkJUnit5 {
		return "", fmt.Errorf("unsupported framework %q (want %s|%s)", framework, FrameworkTestNG, FrameworkJUnit5)
	}
	if cls.ClassName == "" {
		return "", errors.New("RenderKotlin: class name required")
	}
	if len(cls.Cases) == 0 {
		return "", errors.New("RenderKotlin: no cases to render")
	}

	var b strings.Builder
	if cls.Package != "" {
		fmt.Fprintf(&b, "package %s\n\n", cls.Package)
	}
	for _, imp := range neededImports(cls, framework) {
		fmt.Fprintf(&b, "import %s\n", imp)
	}
	b.WriteString("\n")
	b.WriteString("// Generated by `observo jvm stub` — skeleton only. Fill in each body;\n")
	b.WriteString("// the observo:<code> join tag and metadata are already wired.\n")
	if cls.Feature != "" {
		fmt.Fprintf(&b, "@Feature(%s)\n", kotlinString(cls.Feature))
	}
	fmt.Fprintf(&b, "class %s {\n", cls.ClassName)

	seen := map[string]bool{}
	for i := range cls.Cases {
		if i > 0 {
			b.WriteString("\n")
		}
		renderMethod(&b, cls.Cases[i], framework, seen)
	}
	b.WriteString("}\n")
	return b.String(), nil
}

// neededImports returns the sorted import set for the rendered class —
// only the annotations actually used, so the skeleton has no unused imports.
func neededImports(cls StubClass, framework string) []string {
	imps := map[string]bool{}
	switch framework {
	case FrameworkTestNG:
		imps["org.testng.annotations.Test"] = true
	case FrameworkJUnit5:
		imps["org.junit.jupiter.api.Tag"] = true
		imps["org.junit.jupiter.api.Test"] = true
	}
	if cls.Feature != "" {
		imps["io.qameta.allure.Feature"] = true
	}
	for _, c := range cls.Cases {
		if c.Description != "" {
			imps["io.qameta.allure.Description"] = true
			break
		}
	}
	out := make([]string, 0, len(imps))
	for i := range imps {
		out = append(out, i)
	}
	sort.Strings(out)
	return out
}

func renderMethod(b *strings.Builder, sc StubCase, framework string, seen map[string]bool) {
	fn := uniqueFunName(sc, seen)

	layerNote := ""
	if sc.Layer != "" {
		layerNote = " · layer: " + sc.Layer
	}
	fmt.Fprintf(b, "    /** Observo %s%s */\n", sc.Code, layerNote)

	switch framework {
	case FrameworkTestNG:
		fmt.Fprintf(b, "    @Test(groups = [%s])\n", kotlinString("observo:"+sc.Code))
	case FrameworkJUnit5:
		b.WriteString("    @Test\n")
		fmt.Fprintf(b, "    @Tag(%s)\n", kotlinString("observo:"+sc.Code))
	}
	if sc.Description != "" {
		fmt.Fprintf(b, "    @Description(%s)\n", kotlinString(sc.Description))
	}

	fmt.Fprintf(b, "    fun `%s`() {\n", fn)
	if len(sc.Steps) > 0 {
		b.WriteString("        // Steps:\n")
		for i, s := range sc.Steps {
			fmt.Fprintf(b, "        // %d. %s\n", i+1, commentSafe(s))
		}
	}
	fmt.Fprintf(b, "        TODO(%s)\n", kotlinString("implement "+sc.Code))
	b.WriteString("    }\n")
}

// uniqueFunName produces a valid, unique Kotlin backtick function name for
// a case within one class. Duplicate display names are disambiguated with
// the (unique) short code so the class still compiles.
func uniqueFunName(sc StubCase, seen map[string]bool) string {
	base := backtickName(sc.Name)
	if base == "" {
		base = "test " + sc.Code
	}
	name := base
	if seen[name] {
		name = base + " (" + sc.Code + ")"
	}
	// Loop to a guaranteed-unique name — a single attempt could still
	// collide (e.g. the same code appearing twice, or an unlucky overlap).
	for n := 2; seen[name]; n++ {
		name = fmt.Sprintf("%s (%s #%d)", base, sc.Code, n)
	}
	seen[name] = true
	return name
}

// backtickName sanitizes a string into a Kotlin backtick identifier:
// characters illegal inside “ `…` “ (dot, semicolon, colon, slash,
// brackets, angle brackets, backslash, backtick) and newlines are replaced
// with spaces, then runs of whitespace are collapsed.
func backtickName(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch r {
		case '.', ';', ':', '/', '\\', '[', ']', '<', '>', '`', '\n', '\r', '\t':
			b.WriteByte(' ')
		default:
			b.WriteRune(r)
		}
	}
	return strings.Join(strings.Fields(b.String()), " ")
}

// kotlinString wraps s in a double-quoted Kotlin string literal, escaping
// the four sequences that would otherwise break it: backslash, quote,
// dollar (string-template trigger) and newline.
func kotlinString(s string) string {
	r := strings.NewReplacer(
		`\`, `\\`,
		`"`, `\"`,
		`$`, `\$`,
		"\n", `\n`,
		"\r", "",
		"\t", `\t`,
	)
	return `"` + r.Replace(s) + `"`
}

// commentSafe flattens a step onto a single comment line.
func commentSafe(s string) string {
	return strings.Join(strings.Fields(strings.ReplaceAll(s, "\n", " ")), " ")
}

// ClassNameFromFeature derives a PascalCase Kotlin class name from a suite
// name, appending "Test". Falls back to "ObservoStubTest" for an empty or
// symbol-only name.
func ClassNameFromFeature(feature string) string {
	pascal := pascalCase(feature)
	if pascal == "" {
		return "ObservoStubTest"
	}
	if strings.HasSuffix(pascal, "Test") {
		return pascal
	}
	return pascal + "Test"
}

// pascalCase splits on any non-alphanumeric run and Title-cases each word.
// A leading digit is prefixed with "_" so the result is a valid identifier.
func pascalCase(s string) string {
	words := strings.FieldsFunc(s, func(r rune) bool {
		return !((r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9'))
	})
	var b strings.Builder
	for _, w := range words {
		b.WriteString(strings.ToUpper(w[:1]))
		b.WriteString(w[1:])
	}
	out := b.String()
	if out != "" && out[0] >= '0' && out[0] <= '9' {
		out = "_" + out
	}
	return out
}
