package initialize

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// validPlanKey constrains plan_key to chars that are safe both in YAML (no
// quoting needed) and in URL-shaped Observo plan references. Anything else
// risks: YAML parse errors (`: `, leading `*` / `&`), shell glob expansion
// in CI invocations, or backend rejection at create_plan. Caller (cmd/init.go)
// validates the --plan flag against this BEFORE rendering the workflow.
var validPlanKey = regexp.MustCompile(`^[A-Z0-9][A-Z0-9_-]*$`)

// ValidatePlanKey returns nil if key is safe to embed in a YAML scalar
// unquoted. Used for the --plan flag override; auto-derived keys are
// already sanitized by derivePlanName.
func ValidatePlanKey(key string) error {
	if key == "" {
		return fmt.Errorf("plan key is empty")
	}
	if !validPlanKey.MatchString(key) {
		return fmt.Errorf("plan key %q contains characters outside [A-Z0-9_-] (allowed for unambiguous YAML + URL embedding)", key)
	}
	return nil
}

// WorkflowSpec describes what to generate. Renderer is a plain template
// substitution — we deliberately avoid text/template here so customer
// inspection of the YAML diff is straightforward (no template syntax
// leakage on weird inputs).
type WorkflowSpec struct {
	PlanKey      string // observo plan_key, e.g. "EXAMPLE-APP-E2E"
	WorkflowName string // CI display name; defaults to "Observo E2E"
	NodeVersion  string // e.g. "20"; defaults to "20" if empty
}

// WorkflowFileTarget returns the canonical path the generated workflow
// should land at. Customers can override at the prompt; this is the default.
func WorkflowFileTarget(repoRoot string) string {
	return filepath.Join(repoRoot, ".github", "workflows", "observo.yml")
}

// RenderWorkflow produces the YAML body. Mirrors the PRD example but is
// shorter — we don't add the optional `id_tokens:` line (GitHub Actions
// emits an OIDC token automatically when id-token: write permission is
// granted; no per-step token spec needed).
func RenderWorkflow(spec WorkflowSpec) string {
	name := spec.WorkflowName
	if name == "" {
		name = "Observo E2E"
	}
	node := spec.NodeVersion
	if node == "" {
		node = "20"
	}
	return fmt.Sprintf(`# Generated by 'observo init' (OB-356).
# Uses observo-ai/setup@v1 to authenticate via OIDC and create a run, then
# runs Playwright tests. The reporter picks up OBSERVO_RUN_KEY automatically.
name: %s

on:
  pull_request:
  push:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # required for OIDC auth — do not remove
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '%s'

      - uses: observo-ai/setup@v1
        with:
          plan: '%s'

      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npx playwright test

      - name: Finalize Observo run
        if: always()
        run: |
          curl -sS -X POST \
            -H "Authorization: Bearer $OBSERVO_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"status":"auto"}' \
            "https://api.observoai.co/api/runs/$OBSERVO_RUN_KEY:finish"
`, name, node, spec.PlanKey)
}

// WriteWorkflow persists the rendered YAML to dest. If a file already exists
// there, this returns an error — caller decides whether to overwrite (and
// communicates that decision via the prompt). The intent is to never silently
// clobber a customer's existing CI config.
func WriteWorkflow(dest, content string) error {
	if _, err := os.Stat(dest); err == nil {
		return fmt.Errorf("file already exists: %s (refusing to overwrite — patch the existing workflow manually or run with --force)", dest)
	}
	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		return err
	}
	return os.WriteFile(dest, []byte(content), 0o644)
}

// DetectExistingPlaywrightWorkflow returns the path of any existing workflow
// under .github/workflows/ that mentions `playwright test` (case-insensitive).
// Used at the prompt to warn the customer that running `observo init` will
// create a SECOND e2e workflow — they may want to patch the existing one
// instead.
func DetectExistingPlaywrightWorkflow(repoRoot string) (string, error) {
	dir := filepath.Join(repoRoot, ".github", "workflows")
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		if !strings.HasSuffix(e.Name(), ".yml") && !strings.HasSuffix(e.Name(), ".yaml") {
			continue
		}
		path := filepath.Join(dir, e.Name())
		body, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		lower := strings.ToLower(string(body))
		if strings.Contains(lower, "playwright test") || strings.Contains(lower, "@playwright/test") {
			return path, nil
		}
	}
	return "", nil
}
